version: '3.9'
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile.angular
    ports:
      - "8080:80"  # Map the Angular app to port 8080 on your host

  # compodoc:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.compodoc
  #   ports:
  #     - "8501:80"
